version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - ./redis-data:/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_cont
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6321
    ports:
      - 6321:6321
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: always

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: suzii
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: kltn
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3010:8000"
    depends_on:
      - "postgres"
      - "qdrant"
      - "redis"
    volumes:
      - ./backend:/app
